### ISSUE TITLE
Butterfly throws 500

### ISSUE THREAD

**Issue by dominikb1888** [zepheira/backstage#12]
I tried building backstage on ubuntu maverick (with sun-java6-jdk) as outlined on the wiki page. However, when running backstage I get a 404, albeit the resource path in the context is correct. When running butterfly on its own it reports a 500 and the following trace stack:

java.lang.NullPointerException
    at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:500)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1093)
    at clime.messadmin.filter.MessAdminFilter.doFilter(MessAdminFilter.java:104)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:726)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:828)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    at org.mortbay.jetty.nio.BlockingChannelConnector$Connection.run(BlockingChannelConnector.java:163)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:450)

It is possible that my configuration options don't match yours. Thus, I'd be interested if you kept getting similar errors at any point during development. I'd appreciate any help as I would love testing exhibit3.

**Comment by distobj** [comment]
Hi Domink. Sorry, I just noticed this issue - apparently I'm not setup to receive notifications on new issues.

When you say "When running backstage", what exactly were you trying?  Did you follow the steps described in the Authoring wiki page to setup an Exhibit?

**Comment by dominikb1888** [comment]
Hi Mark,

yes i did follow the tutorial. Seemed to be a no-brainer. When running backstage I was following these steps:
1. in the backstage directory: ./backstage
2. opened browser and went to localhost:8181
3. Received a 404 with the following link to click to the exhibit directory: /backstage ---> org.mortbay.jetty.plugin.Jetty6PluginWebAppContext@a83c2a{/backstage,/home/quickstart/e3src/butterfly/engine/src/main/webapp}
4. Came to a site with the following output: HTTP ERROR: 404, Couldn't find the specified resource, RequestURI=/backstage/

I then started butterfly in a separate terminal (so backstage and butterfly were running at the same time) and received the above error when accessing butterfly at localhost:8081. I changed the port for butterfly because I have jenkins already running at 8080.

I also receive the following not on startup of each of the systems: "No Transaction manager found - if your webapp requires one, please configure one."

I am not a Jetty Expert by all means. However I am in the process of porting the exhibit drupal module and would have wanted to test exhibit3 and exhibit3-backstage.

Thanks for taking the time!
Dominik

**Comment by distobj** [comment]
Hey.  Backstage doesn't serve the HTML, and instead just offers an HTTP interface that's used by the scripts that are loaded when you create some Exhibit HTML and link in those scripts.  I will try to make that more obvious in the Wiki pages.

You shouldn't run butterfly separately; Butterfly is a web-app framework, and Backstage is a Butterfly app, so when you run Backstage using the "backstage" script, you're running Butterfly+Backstage.

BTW, I also receive the "No Transaction manager found" notice; not to worry, that's not an error.

**Comment by dominikb1888** [comment]
Now that would explain things. Thank you very much for the clarification. Should have probably read the other wiki entry more carefully and made proper sense of that... 

Running butterfly separately was just to check if anything is wrong with this. Babel did work though, which got me into thinking the other two should produce some kind of HTML as well.
