### ISSUE TITLE
TypeError: Cannot call method "hasComponentsChangingState" of undefined

### ISSUE THREAD

**Issue by dominikb1888** [zepheira/backstage#18]
I am receiving the session back from the http request with a 201 now. However the data itself is not being returned instead I receive the following error.

Butterfly Error
Butterfly caught the following error while processing the request:
org.mozilla.javascript.EcmaError: TypeError: Cannot call method "hasComponentsChangingState" of undefined (file:/home/quickstart/e3src/backstage/modules/backstage/MOD-INF/server.js#289)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3350)
    at org.mozilla.javascript.ScriptRuntime.constructError(ScriptRuntime.java:3340)
    at org.mozilla.javascript.ScriptRuntime.typeError(ScriptRuntime.java:3356)
    at org.mozilla.javascript.ScriptRuntime.typeError2(ScriptRuntime.java:3375)
    at org.mozilla.javascript.ScriptRuntime.undefCallError(ScriptRuntime.java:3394)
    at org.mozilla.javascript.ScriptRuntime.getPropFunctionAndThis(ScriptRuntime.java:2026)
    at org.mozilla.javascript.Interpreter.interpretLoop(Interpreter.java:3081)
    at script.processBackChannel(file:/home/quickstart/e3src/backstage/modules/backstage/MOD-INF/server.js:289)
    at script.clearAllFacetRestrictions(file:/home/quickstart/e3src/backstage/modules/backstage/MOD-INF/server.js:443)
    at script.process(file:/home/quickstart/e3src/backstage/modules/backstage/MOD-INF/server.js:54)
    at org.mozilla.javascript.Interpreter.interpret(Interpreter.java:2394)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:162)
    at org.mozilla.javascript.ContextFactory.doTopCall(ContextFactory.java:393)
    at org.mozilla.javascript.ScriptRuntime.doTopCall(ScriptRuntime.java:2834)
    at org.mozilla.javascript.InterpretedFunction.call(InterpretedFunction.java:160)
    at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.process(ButterflyModuleImpl.java:461)
    at edu.mit.simile.butterfly.ButterflyModuleImpl$Controller.run(ButterflyModuleImpl.java:438)
    at org.mozilla.javascript.Context.call(Context.java:577)
    at org.mozilla.javascript.ContextFactory.call(ContextFactory.java:503)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.processScript(ButterflyModuleImpl.java:689)
    at edu.mit.simile.butterfly.ButterflyModuleImpl.process(ButterflyModuleImpl.java:502)
    at edu.mit.simile.butterfly.Butterfly.service(Butterfly.java:511)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
    at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:487)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1093)
    at clime.messadmin.filter.MessAdminFilter.doFilter(MessAdminFilter.java:104)
    at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1084)
    at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:360)
    at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:216)
    at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
    at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:726)
    at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:405)
    at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:206)
    at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
    at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:152)
    at org.mortbay.jetty.Server.handle(Server.java:324)
    at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:505)
    at org.mortbay.jetty.HttpConnection$RequestHandler.headerComplete(HttpConnection.java:828)
    at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:514)
    at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:211)
    at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:380)
    at org.mortbay.jetty.nio.BlockingChannelConnector$Connection.run(BlockingChannelConnector.java:163)
    at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:450)

**Comment by distobj** [comment]
Hi Dominik. This week we've made some changes to how things are built.  Since you got it running, it probably means you're using the old code, so if you could please try again with the updated build instructions (which uses a newer version of Butterfly), I'd appreciate it.

**Comment by dominikb1888** [comment]
Hi Mark,

saw that and got everything working now. This really rocks! I've also tested it with a large number of drupal nodes (10000) and things are still quick. Will test with more nodes in the future.

Thanks for this tool and the nice support!

Best,
Dominik
