### ISSUE TITLE
steps to run demo

### ISSUE THREAD

**Issue by qbalsoftware** [zepheira/backstage#21]
hey folks -- i have built everything per the readme, and now I want to run the demo in backstage/demos/sweden-europeana. what steps do I have to perform to get the demo running?

./post.rb 
201
{:expires=>"Thu, 01 Jan 1970 00:00:00 GMT", :set_cookie=>["host=.butterfly;Path=/;Expires=Fri, 21-Oct-11 22:29:11 GMT", "JSESSIONID=148oam22mn1j6;Path=/"], :location=>"/data/5db3711d", :content_type=>"text/plain; charset=utf-8", :content_length=>"26", :server=>"Jetty(6.1.22)"}
Data successfully uploaded

index.html

```
link href="http://localhost:8181/data/5db3711d" rel="exhibit/data"


script src="http://localhost:8181/backstage/exhibit/api/exhibit-api.js?autoCreate=false&postLoad=true&js=http://localhost:8181/backstage/api/backstage-api.js"
```

15:28:58.706 [server                   ] Starting autoreloading scanner...  (184ms)
15:30:36.771 [backstage.collection     ] Failed to update facet (0ms)
edu.mit.simile.backstage.model.data.ExpressionException: No property can be aliased to 'creator'
    at edu.mit.simile.backstage.model.data.Path.computeOutput(Path.java:75)
    at edu.mit.simile.backstage.model.data.Expression.computeOutputOnItem(Expression.java:46)
    at edu.mit.simile.backstage.model.ui.facets.ListFacet.update(ListFacet.java:121)
    at edu.mit.simile.backstage.model.data.Collection.updateOneFacet(Collection.java:86)
    at edu.mit.simile.backstage.model.data.Collection.addFacet(Collection.java:60)
    at edu.mit.simile.backstage.model.ui.facets.ListFacet.configure(ListFacet.java:80)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
    at java.lang.reflect.Method.invoke(Method.java:597)
    at org.mozilla.javascript.MemberBox.invoke(MemberBox.java:161)
    at org.mozilla.javascript.NativeJavaMethod.call(NativeJavaMethod.java:247)
    at org.mozilla.javascript.optimizer.OptRuntime.call2(OptRuntime.java:76)

I was consistently getting this error then I stopped the server and restarted, and now I'm not getting it.  Now I'm getting  back "0 results in total"

I also see that the content-length is '26' -- so not sure what is going on here...

it would be nice to have a simple walkthru soup-to-nuts on how to update the demo data, and then run the demo. 

thanks -- paul

**Comment by qbalsoftware** [comment]
update -- I got it working. I manually used curl to update the data file 

curl -i -H "Content-Type: application/json" -X POST -T europeana-swe.json  http://localhost:8181/backstage/data

I had been using a ruby script and the restclient gem. Not sure why that was not working as I use it for updating to a mongodb -- but anyhow I have a local staging server up

Thanks for all the great work!

**Comment by distobj** [comment]
I'm glad you figured it out, qbal. I've gone ahead and added your curl command to the HttpInterface document. Thanks!
